source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '10.0'

target 'Chama' do
    
    pod "SDWebImage"
    pod 'JGProgressHUD'
    pod 'IQKeyboardManagerSwift'
    pod 'Alamofire', '~> 4.4'
    pod 'EVReflection' # swift object model for parse etc
    pod 'Fabric'
    pod 'Stripe'
    pod 'Crashlytics', '~> 3.12.0'
    pod 'Toast-Swift', '~> 4.0.0'
    pod 'Instabug'
    pod 'SwiftLog', '~> 1.0.0'
    pod 'Localize-Swift', '~> 2.0'
    #pod 'SwiftyShadow', '~> 1.6.0'
    pod 'ShadowView' #new
    pod 'PopupDialog', '~> 0.9' # custom dialog
    #pod "ESPullToRefresh"
    pod 'DKImagePickerController'
    pod 'DynamicBlurView'
    pod 'SidebarOverlay'
    pod 'Material'
    pod 'Charts'
    
    #pod 'LocationPicker'
    
end
